// Prop validation
export const LBX_PROP_REQUIRED = "LBX_PROP_REQUIRED"
export const LBX_INVALID_VARIANT = "LBX_INVALID_VARIANT"
export const LBX_INVALID_PROP_TYPE = "LBX_INVALID_PROP_TYPE"
export const LBX_UNKNOWN_PROP = "LBX_UNKNOWN_PROP"

// Composition validation
export const LBX_INVALID_CHILD = "LBX_INVALID_CHILD"
export const LBX_INVALID_PARENT = "LBX_INVALID_PARENT"
export const LBX_MAX_DEPTH_EXCEEDED = "LBX_MAX_DEPTH_EXCEEDED"
export const LBX_FORBIDDEN_COMBINATION = "LBX_FORBIDDEN_COMBINATION"

// Slot validation
export const LBX_SLOT_REQUIRED = "LBX_SLOT_REQUIRED"
export const LBX_INVALID_SLOT_CHILD = "LBX_INVALID_SLOT_CHILD"
export const LBX_SLOT_CARDINALITY = "LBX_SLOT_CARDINALITY"

// Accessibility validation
export const LBX_ACCESSIBILITY_MISSING_ARIA = "LBX_ACCESSIBILITY_MISSING_ARIA"
export const LBX_ACCESSIBILITY_FOCUS_REQUIRED = "LBX_ACCESSIBILITY_FOCUS_REQUIRED"
export const LBX_ACCESSIBILITY_KEYBOARD_REQUIRED = "LBX_ACCESSIBILITY_KEYBOARD_REQUIRED"
export const LBX_ACCESSIBILITY_ROLE_INVALID = "LBX_ACCESSIBILITY_ROLE_INVALID"

// Responsive validation
export const LBX_RESPONSIVE_RULE_MISSING = "LBX_RESPONSIVE_RULE_MISSING"
export const LBX_RESPONSIVE_CONTRACT_INCOMPLETE = "LBX_RESPONSIVE_CONTRACT_INCOMPLETE"

// Metadata validation
export const LBX_METADATA_SCHEMA_INVALID = "LBX_METADATA_SCHEMA_INVALID"
export const LBX_METADATA_INCOMPLETE = "LBX_METADATA_INCOMPLETE"
export const LBX_METADATA_CONTRACT_MISMATCH = "LBX_METADATA_CONTRACT_MISMATCH"
